apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ml-staging

configMapGenerator:
  - name: ml-api-config
    behavior: merge
    literals:
      - environment=staging
      - log_level=INFO

replicas:
  - name: ml-api
    count: 3
