"""
Augment training data with additional RLHF pairs and instruction prompts.
Generates Q&A pairs from the novel text and detailed analysis tasks.
Run: python augment_training_data.py
"""
import json, os, glob, re, textwrap

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
CONTENT_DIR = os.path.join(os.path.dirname(__file__), "content", "the-everglades-cipher")

# ---------------------------------------------------------------------------
# Load all novel text for context-grounded Q&A
# ---------------------------------------------------------------------------
all_files = sorted(glob.glob(os.path.join(CONTENT_DIR, "*.txt")))
novel_text = {}
for path in all_files:
    with open(path, encoding="utf-8") as f:
        key = os.path.basename(path).replace(".txt", "")
        novel_text[key] = f.read()

# ---------------------------------------------------------------------------
# Additional RLHF pairs (20 more, covering new appendix material and deeper analysis)
# ---------------------------------------------------------------------------

EXTRA_RLHF = [
    {
        "prompt": "What navigational capabilities did the Knights Templar possess in the early fourteenth century?",
        "chosen": "The Iberian Templar maritime network in the early fourteenth century operated with the full range of navigational tools available to the best European mariners of the period. They possessed the magnetic compass, in widespread use among Mediterranean navigators since the late twelfth century, which allowed reliable directional steering regardless of visibility. They used portolan charts — the class of navigational chart with accurately rendered coastlines and magnetic rhumb lines — and had access to Arabic and Hebrew navigational manuscripts through the Templar archive at Cyprus. Their navigators practiced dead reckoning for open-ocean position keeping, and basic solar and stellar observation for latitude determination. These capabilities were sufficient for the Atlantic crossings to the Canary Islands, Madeira, and the Azores that Templar-connected mariners were conducting before the dissolution, and, the novel proposes, for a crossing to the Caribbean following the northeast trade winds from the Canaries.",
        "rejected": "The Templars were skilled sailors who had boats and could navigate. They knew about winds and currents from their time in the Mediterranean and Atlantic. This gave them enough knowledge to potentially make an Atlantic crossing. The novel suggests they used these skills to sail to the Caribbean."
    },
    {
        "prompt": "What is the historical significance of the La Rochelle fleet's disappearance?",
        "chosen": "The disappearance of the Templar fleet from La Rochelle on the night of October 12-13, 1307 — the evening before Philip IV's arrest order was executed — is the most enduring mystery of the Templar dissolution. The fleet had been the principal Atlantic maritime asset of the French Templars, and when royal agents arrived at the harbor on the morning of the arrests, it was empty. Eighteen to twenty vessels had departed without leaving any subsequent record of their destination or fate. The standard historical record offers no confirmed answer. The candidates — Portugal, Scotland, the Atlantic islands — remain speculative because no subsequent port record documents the fleet's arrival. The Codex Almeida, if authentic, proposes that at least a portion of the fleet executed the archive transfer voyage to the Caribbean. This would explain the fleet's disappearance without contradiction: vessels that crossed to the Western Caribbean and returned would have reentered Atlantic traffic far from La Rochelle, without Templar markings, and blended back into normal maritime activity.",
        "rejected": "The La Rochelle fleet disappeared before the arrests in 1307. No one knows where it went. The novel suggests it went to the Caribbean to hide the archive. This is one of history's great mysteries."
    },
    {
        "prompt": "How does the Order of Christ connect the Templar dissolution to the Age of Discovery?",
        "chosen": "The Order of Christ was established by Portuguese King Denis I in 1319 as an explicit successor organization to the Knights Templar, which Denis had refused to dissolve in Portugal. The new Order absorbed the Portuguese Templar personnel, assets, and institutional knowledge — including navigational charts, sailing directions, and the accumulated maritime experience of the Templar fleet's Atlantic operations. This institutional inheritance positioned the Order of Christ as the patron of Portuguese maritime exploration in the fifteenth century. Henry the Navigator, who organized the systematic exploration of the African coast beginning in the 1420s, was an Order of Christ member and eventually its Grand Master. The Portuguese navigational advantage in the fifteenth century — the ability to work out the wind systems and routes that would eventually take Vasco da Gama to India — was built on a foundation of accumulated maritime knowledge that traced back, through the Order of Christ, to the Templar maritime tradition. The Codex Almeida's fictional contribution to this chain is the claim that Templar knowledge of Atlantic wind patterns, specifically the trade winds and westerlies that make transatlantic navigation efficient, was preserved in the Order's institutional memory.",
        "rejected": "The Order of Christ inherited the Templar assets and knowledge in Portugal. This included navigational knowledge that was later used by Portuguese explorers. Henry the Navigator was part of this Order. So there is a connection between the Templars and the Age of Discovery through Portugal."
    },
    {
        "prompt": "Describe the physical preservation conditions in the Cayo Espiritu cave.",
        "chosen": "The Cayo Espiritu cave's preservation of the archive for seven centuries is attributable to four factors working in combination. First, thermal stability: the cave's limestone mass maintains a near-constant temperature of approximately 23 degrees Celsius, within the range of modern archival standards. Second, humidity control: the cave's geometry creates a tidal pressure cycle that exchanges air through the entrance passage while maintaining the interior air pocket at approximately 55-60% relative humidity — significantly lower than the exterior Caribbean atmosphere of 75-85%. The limestone's hygroscopic properties cause moisture to condense on the outer surfaces near the entrance rather than in the interior. Third, container design: the archive boxes are lead-lined oak with pitch-coated exterior, a system that prevents moisture penetration and provides a neutral chemical environment for the documents inside. Fourth, the choice of vellum and parchment over paper: treated animal skin is significantly more durable than paper under variable humidity conditions and maintains integrity in the humidity range the cave provides. Together these factors created passive archival conditions that, without any active management over seven centuries, preserved materials that a modern archivist would be satisfied to recover.",
        "rejected": "The cave had good natural conditions that preserved the documents. The temperature and humidity were stable, the cave was isolated from the outside, and the boxes were sealed. The combination of the cave's natural environment and the good quality of the containers meant the documents survived for 700 years."
    },
    {
        "prompt": "What is the significance of the portolan charts found in the Cayo Espiritu archive?",
        "chosen": "Three of the twelve navigational charts and portolan maps recovered from the Cayo Espiritu archive are described in the preliminary assessment as predating the known portolan tradition by forty years and mapping Atlantic coastlines that, in the standard historical account, were not reached by European navigators until the mid-fifteenth century. If authenticated, these charts would constitute documentary evidence of pre-Columbian European navigation significantly beyond what is currently documented — more extensive than the Norse Vinland settlements and potentially including knowledge of Atlantic routes used in the fifteenth-century Portuguese discoveries. The scholarly caution surrounding these charts is appropriate: the implications are substantial enough to require a standard of evidence considerably higher than the preliminary assessment provides. The novel is deliberately careful not to assert that the charts are authentic, only that their preliminary assessment suggests they may be and that careful scholarly work is proceeding. The charts are, in this sense, the archive's most historiographically volatile element.",
        "rejected": "The charts found in the archive are very old and show coastlines that Europeans supposedly hadn't reached yet. If they are real, this would change our understanding of early Atlantic exploration. Scholars are being careful about confirming this. The charts could be evidence of pre-Columbian European exploration."
    },
    {
        "prompt": "How does Jake Malone's character develop through the course of the novel?",
        "chosen": "Jake Malone does not undergo a conventional character arc in the sense of fundamental transformation. He is who he is at the beginning and he is still who he is at the end. What the novel provides instead is a gradual revelation of the depth and texture of that character: the ways in which his patience, his precision, and his particular form of attention are not just professional tools but the expression of a philosophy he has arrived at through experience. The Vasquez-Cortez case is not what changes Jake; it is what reveals him. It gives him a case that is large enough to require everything he has — not just the investigative skills but the patience, the tolerance for complexity, and the specific human quality of being able to receive other people's private revelations without making them about himself. His relationship with Arturo, over the course of the novel, is a minor friendship that neither of them discusses: two people who understand each other across a difference of generations and temperament. The epilogue places Jake back on his houseboat deck, working on the next case, which is not a failure of resolution but an accurate portrait of a man for whom the work is the life.",
        "rejected": "Jake starts as a typical private detective who takes on a simple missing persons case. Through the investigation he learns about a much bigger historical mystery. He grows as a character by dealing with the Everglades, the Caribbean voyage, and the confrontation with the antagonists. By the end he has completed a major case and has deeper relationships with the other characters."
    },
    {
        "prompt": "What is the ecological significance of Elena's reef research to the novel's themes?",
        "chosen": "Elena's research on the Florida Reef Tract operates as the novel's ecological counterpoint to its archival and historical themes. Where the archive story is about preservation succeeding — materials that survived seven centuries because the right conditions were maintained — the reef story is about preservation under threat: an ecosystem that has sustained significant damage from thermal stress, runoff, and mechanical disturbance, and that is showing partial recovery in response to improved water quality management and coral recruitment programs. The parallel the novel draws is explicit: both stories are about what survives, and under what conditions. Both require sustained, patient, accurate observation — the kind that Arturo practices in his back room and Elena practices on her dive slates. Nacho's thirty years of dive logs are evidence for both stories simultaneously: they document the reef's health history and they document the acoustic anomaly that leads to the cave. The coincidence of these two significances in a single set of records is the novel's implicit argument about the value of meticulous long-term documentation: you cannot predict what your records will eventually prove, but if they are accurate and sustained, they will eventually prove something.",
        "rejected": "Elena's research about the reef parallels the themes of preservation and history in the novel. The reef is threatened but recovering, similar to how the archive was preserved but forgotten. This environmental theme adds depth to the story. The connection between the dive logs and the archive discovery shows how different kinds of knowledge can be useful in unexpected ways."
    },
    {
        "prompt": "How does the novel use silence and withholding as narrative devices?",
        "chosen": "Silence and withholding are the novel's primary emotional register. The novel's most significant relationship — Elena and Arturo — is defined by what they do not say to each other for fifty years: she does not ask about the letter in the closet; he does not tell her about Rosa Castillo. The narrative treats this mutual withholding not as dysfunction but as a particular form of care: they are protecting each other from the cost of opening what they both know is there. Jake's investigative voice is characterized by the same withholding: he registers much more than he reports, and his narration has the quality of a man who has learned that not saying everything he thinks is a form of professional and personal respect. Diego de Almeida's cipher system is itself a form of sophisticated withholding: the information is present in the document, but withheld from anyone who does not know how to read it. The novel's resolution comes when the withholding ends: when Arturo tells Elena everything in the galley, when the cipher is finally decoded, when the archive is finally opened. The emotional weight of these moments depends on the accumulated restraint of everything that came before them.",
        "rejected": "The characters in the novel often don't say what they know or feel. This creates tension and character depth. Elena and Arturo's relationship is defined by things they don't discuss. The cipher itself is a form of withholding information. When information is finally revealed, it is more powerful because of the restraint before it."
    },
    {
        "prompt": "What is the role of institutional memory in the novel?",
        "chosen": "Institutional memory is the novel's most complex and double-edged concept. The Templar Order's institutional memory — its navigation charts, its sailing directions, its intelligence networks, its accumulated knowledge of Mediterranean and Atlantic waters — is what makes the archive transfer possible and what eventually flows into the Order of Christ and the Portuguese Age of Discovery. This is institutional memory working as it should: knowledge preserved, transmitted, and eventually used. But the novel also examines institutional memory working against transparency: Philip IV's intelligence apparatus, the Vatican's interest in suppressing the letters that document its relationship with the French crown, the Cuban government's interest in controlling information about pre-revolutionary aristocratic families. All of these are institutional memories that institutions would prefer remained unavailable. The archive is, in this sense, a collection of institutional memories that other institutions wanted destroyed, preserved by one institution (the Templars, specifically Diego's portion of it) that understood that accuracy mattered more than political convenience. This is the Codex Almeida's ethical center: the choice to preserve what powerful parties wanted eliminated, in a form that could survive without their permission.",
        "rejected": "The novel deals with how institutions remember and preserve information. The Templars preserved their documents but other institutions wanted certain information destroyed. The archive represents a form of memory that survived despite political pressure. This theme runs through both the historical and present-day storylines."
    },
    {
        "prompt": "Compare the writing styles used for the present-day thriller sections and the historical interludes.",
        "chosen": "The novel employs two distinct prose registers that alternate throughout. The present-day sections are written in a close third-person limited perspective focused on Jake, with the spare, precise style of the hard-boiled tradition: short declarative sentences, minimal editorializing, dialogue that carries subtext through what is omitted, physical and environmental detail rendered with the attention of a trained observer rather than a tourist. The rhythm is functional, forward-moving, organized around observation and action. The historical interludes are written in present tense — an unusual choice for historical fiction, but one that creates a quality of immediacy — with a different register: more lyrical, with the sustained sensory immersion of Elizabeth Kostova's historical fiction, attentive to the specific texture of medieval daily experience (cold stone, the smell of tallow candles, the weight of wet wool) without making these details picturesque. Diego's consciousness is rendered from within, in a voice that is intelligent, dry, and occasionally sardonic in the way that competent people under pressure are occasionally sardonic. The two registers reinforce each other: the present-day spare style makes the reader value precision and observation; the historical lyrical style makes the reader slow down and inhabit the fourteenth century. When the two converge — in the final historical interlude that overlaps with the Miss Biscayne's approach to Cayo Espiritu — the effect depends on the reader having internalized both registers.",
        "rejected": "The thriller sections are written in a fast-paced, modern style while the historical sections are more detailed and descriptive. This contrast helps distinguish the time periods and creates different reading experiences. The thriller style keeps the pace up while the historical style provides depth and atmosphere. The two styles come together at the end of the novel."
    },
    {
        "prompt": "What deleted scene provides the most insight into Jake and Nacho's friendship?",
        "chosen": "The deleted dock scene from Chapter Nine is the most sustained portrait of Jake and Nacho's friendship as a complete thing rather than a plot-relevant relationship. The scene takes place at four-thirty in the morning on Nacho's dock at Big Pine Key, a time and place that signals immediately that their friendship has a long, specific history: Jake has learned over forty years that sitting on the dock at four-thirty with Nacho is what being Nacho's friend means. The scene's emotional work is in what is not said: the conversation about the island and the manuscript proceeds with the brevity of two people who have been communicating in shorthand for four decades. The running joke about Jake having 'non-manuscript cases' (the Brennan thing) illustrates the self-aware humor of a long friendship. Nacho's observation that twelve-year-old Jake said he was going to 'find out things' rather than 'be a detective' is the scene's best line — it illuminates Jake's actual motivation (understanding, not solving) more precisely than any passage in the main text. The scene was removed for pacing but represents the fullest available portrait of what Jake is like when he is not working.",
        "rejected": "The deleted dock scene shows Jake and Nacho's friendship in the early morning. They talk about the investigation while Nacho makes coffee. It shows their long history together and their easy way of communicating. This scene was cut from the final novel for pacing reasons."
    },
    {
        "prompt": "How does Arturo's scholarly method reflect the novel's broader themes?",
        "chosen": "Arturo's scholarly practice is the novel's primary embodiment of its values. He works in the way that the novel proposes all important work should be done: slowly, precisely, without external pressure, with the discipline to distinguish between what the evidence shows and what he would like it to show. He spent thirty-four years on the Codex because that was how long it took to be certain, not merely confident. He did not publish preliminary findings — not because he was secretive (though he was) but because preliminary findings are not findings, and the responsible relationship between a scholar and his evidence is to wait until the evidence is sufficient. This methodological patience is also a form of character: it is what allows him to raise Elena alone, run a bookshop, and decode a medieval cipher simultaneously, without any of these three activities compromising the others. The novel proposes that precision and patience are not merely professional virtues but human ones — that the same quality of attention that makes a good scholar also makes a good father and a good neighbor. Arturo is the novel's exemplar of this proposition.",
        "rejected": "Arturo's scholarly method is careful and thorough, which reflects the novel's themes of patience and precision. He spent 34 years on the Codex because he wanted to be certain before publishing. This patience extends to his personal life as well. His way of working is presented as a model for how important things should be approached."
    },
    {
        "prompt": "What is the significance of the novel's ending image — Arturo at his worktable with a new manuscript?",
        "chosen": "The final image of Arturo at his worktable, with a new manuscript problem, is a structural echo of the novel's opening description of him — the lamp, the facsimile pages, the late-night quiet — and functions as the novel's quiet statement of values. The ending refuses the usual resolution of the thriller plot (crisis resolved, protagonist returns to normal life, normal life is visibly better for the experience) in favor of something more honest: Arturo is back at his worktable because the worktable is where he lives. The Codex Almeida is solved and the archive is found and Elena knows about Rosa Castillo and these are all important resolutions, but they do not change what Arturo does in the evenings. He sits under the lamp and looks at pages that mean something. He is sixty-five pages into a seventeenth-century navigational text that arrived from a Lisbon estate sale. He turns the first page. He begins. The word 'begins' is the novel's last verb, and its tense is present: not past (he began), not continuous (he was beginning), but the raw present that indicates an action still in process. He is not finishing; he is beginning again. This is the novel's argument about a life well spent.",
        "rejected": "The ending shows Arturo going back to his normal life as a bookseller and scholar. He has a new manuscript to work on which symbolizes continuity. After all the adventure and discovery, life goes on. The image suggests that the important thing is the ongoing work, not just the big discoveries."
    },
    {
        "prompt": "How does the novel portray the Cuban-American community of Little Havana?",
        "chosen": "Little Havana in the novel is not the tourist-facing image of the neighborhood — the painted murals, the cigar rollers, the curated nostalgia of Calle Ocho as attraction — but a working neighborhood where a bookshop has been operating for fifty-four years on a mixed block of businesses, where the ventanitas serve cortaditos to regulars rather than Instagram visitors, where Domino Park is genuinely for dominos rather than for watching people play dominos. Arturo's integration into this community is complete and unremarkable: he has been here since 1973, he is known by the neighborhood's specific knowledge of long-term residents (he is 'the one with the bookshop,' 'the one who kept Elena in university'), and the neighborhood has changed in the ways that Miami neighborhoods change — generationally, politically, commercially — while the bookshop has provided a continuity. The Cuban-American community is not romanticized. It is rendered with the specific detail of a place that has been observed over time: the generational tensions between the first-wave exiles and their American-raised children, the changing relationship to the Castro government and its successors, the neighborhood's economic history. Elena is a product of this place — she grew up above the bookshop on this street — and her marine biology career at UM is itself a kind of continuity, the neighborhood's habit of education applied to a specific scientific vocation.",
        "rejected": "The novel portrays Little Havana as a real community rather than a tourist attraction. Arturo has lived there for decades and is part of the neighborhood. The community has its own history and culture. Elena grew up there and it shaped who she became. The neighborhood provides an authentic Miami backdrop for the story."
    },
    {
        "prompt": "What does the novel say about the nature of historical evidence?",
        "chosen": "The novel makes a sustained argument about historical evidence through its structure and through the characters' relationships to their sources. The argument has three strands. First, evidence is often in plain sight: the Codex Almeida was in a Seville archive, accessible in principle to any scholar who examined it. The cipher was not broken for seven centuries not because it was hidden but because no one with the right combination of skills and patience looked at it long enough. Second, evidence requires interpretation, and interpretation requires discipline: the distance between what the evidence says and what the interpreter wants it to say is precisely the distance between good scholarship and bad. Arturo's thirty-four years of work is largely the work of maintaining that discipline — being willing to slow down, verify, and revise rather than claim certainty before it exists. Third, evidence is created by the choices of its creators, and those choices were often made under pressure. Philip IV wrote the letters in cipher and had them transmitted through a trusted intermediary; the choice to use cipher reveals that he knew the content was compromising. Diego chose vellum over paper and lead-lined boxes over oak alone; the choices reveal that he was designing for the long term. The evidence in the Cayo Espiritu archive is evidence not only of what it says but of how it was made — and the how is often as informative as the what.",
        "rejected": "The novel explores how we understand history through evidence. The archive provides direct evidence of what actually happened with Philip IV and the Templars. The novel shows that historical evidence can survive for centuries if preserved properly. It also shows that interpreting evidence requires skill and care."
    },
    {
        "prompt": "How does the Miss Biscayne voyage function as a structural device?",
        "chosen": "The Miss Biscayne voyage is a structural hinge: the point at which the novel transitions from its mode as a Miami procedural thriller to its mode as a Caribbean historical resolution. Before the voyage, the plot is organized around investigation and urgency: finding Arturo, understanding the Codex, preventing Andrade. After the voyage begins, the urgency relaxes because the external threat has been resolved (Andrade is in custody) and what remains is completion rather than rescue. The voyage is the time in which the resolution develops: the galley conversation where Arturo tells Elena about Rosa Castillo, the night watches where Jake and Arturo talk about Diego, the final confirmation of the modal coordinates. The Caribbean crossing is also a physical parallel to Diego's voyage — same water, roughly the same route, a very different vessel and very different equipment — and the novel uses this parallel to bring the historical and present-day narratives into convergence for the first time. The island on the horizon at the end of the voyage is seen simultaneously in two times: from the Miss Biscayne's deck in 2024, and from Diego's vessel in 1312. The convergence is the novel's structural climax, and the voyage is what makes it possible.",
        "rejected": "The voyage to Cayo Espiritu is both a physical journey and a thematic journey in the novel. It marks the shift from the investigative part of the story to the resolution. During the voyage the characters have important conversations and the historical and present-day plots come together. The voyage parallels Diego's original journey in the 14th century."
    },
    {
        "prompt": "What techniques does Diego de Almeida use to verify his cipher system's accuracy?",
        "chosen": "Diego's cipher system includes three distinct verification mechanisms. The first is the grille cipher's coordinate confirmation: the grille template, when placed over the Codex pages, reveals not just the location coordinates but a brief phrase in Portuguese that translates as 'the island that hears itself' — a description of the cave's acoustic property that allows anyone who reaches the correct location to confirm they have decoded correctly without requiring any additional knowledge. The second is the internal redundancy of the modal cipher: the same coordinate string is encoded twice, in two separate passages of the musical notation, using different starting points in the mode sequence. A decoder who reads both passages and gets the same result can be confident the decoding is correct; a decoder who gets different results knows to recheck. The third is the physical site confirmation: the Phrygian dominant resonance of the cave is the same interval as the final modal value in the cipher sequence, making the site self-identifying to anyone who arrives with knowledge of the cipher. Together these mechanisms form a verification chain: the coordinates are confirmed by the phrase, the phrase is confirmed by the redundant encoding, and the site is confirmed by the acoustic property. Diego designed a system that would be reliable without an institutional guardian, which was the specific constraint he was working under.",
        "rejected": "Diego built verification into his cipher system to ensure accuracy. The cipher had redundant elements that would confirm the correct decoding. The cave's natural acoustic properties also helped confirm the location. These features made the cipher self-verifying so that anyone who correctly decoded it would know they had the right answer."
    },
    {
        "prompt": "How does the novel handle the moral ambiguity of preserving versus revealing sensitive historical information?",
        "chosen": "The novel takes a clear position on the preservation-versus-revelation question, but it earns that position by taking the opposing view seriously. The case for suppression is presented through Father Calvino, whose argument is not simply self-interest: he points out that the Philip IV letters document a period of papal-French crown relations that the current Church did not create and cannot be held responsible for, and that releasing them without careful historical contextualization will generate media coverage that is more damaging than enlightening. This is not an entirely dishonest argument. Elena's counter-position — that the question of custody should follow the question of purpose: who will take best care of the documents and ensure scholarly accessibility? — is the novel's answer, but it is stated as a principle rather than a rhetorical victory. The novel resolves the tension not by adjudication but by the practical fact of the archive's existence: it is found, it is real, and the question of whether to reveal it is no longer meaningful. What remains is the question of how to reveal it responsibly, which is a harder and more interesting question. The legal framework for custody is still being negotiated at the novel's end, and this incompleteness is honest rather than evasive.",
        "rejected": "The novel deals with whether to reveal sensitive historical information. Some characters want to suppress the Philip IV letters. Elena argues for scholarly access. The novel ultimately comes down on the side of preserving historical truth while acknowledging the complications. The legal situation at the end is not fully resolved, which reflects real-world complexity."
    },
    {
        "prompt": "What is the significance of the Everglades as a setting for Arturo's captivity?",
        "chosen": "The Everglades is both practically and thematically appropriate as the location of Arturo's captivity. Practically: its geographical isolation — accessible only by airboat, surrounded by water and sawgrass, without roads or landmarks that allow orientation from the outside — makes it functionally secure as a holding location. The same qualities that make it a federal wilderness reserve (remoteness, ecological sensitivity, controlled access) make it useful to people who want to conduct operations without interference. Thematically: the Everglades is Florida's landscape of revelation. It is the place that the city cannot reach and cannot control, the landscape that operates by its own rules and resists development not through human choice but through its own physical reality. It is also the landscape that Marjory Stoneman Douglas, who saved it, described as a river rather than a swamp — something that appears still but is in continuous motion, organized around a slow, invisible logic. Arturo in the fish camp, spending eleven days with his manuscript notes, is in some sense where the logic of his thirty-four-year project has been all along: in a place that appears static but is moving, slowly, toward a destination that has always been there.",
        "rejected": "The Everglades setting for Arturo's captivity works because of its remoteness and isolation. The landscape makes it difficult to find him and requires knowledge of the area to rescue him. The Everglades also represents a kind of Florida that is different from Miami, wild and governed by nature rather than people. This contrast is part of the novel's use of Florida's diverse landscapes."
    },
    {
        "prompt": "What additional detail about Philip IV's intelligence operations do the archive letters reveal?",
        "chosen": "The four Philip IV letters in the archive document an intelligence partnership between the French crown and the Templar Order that operated from at least 1296 — eleven years before the dissolution. The first letter, addressed to Grand Master Thibaud Gaudin in 1296, requests a full accounting of Templar agents in the papal Curia, all intelligence from Avignon in the preceding six months, the names and dispositions of agents in the intelligence service of Pope Boniface VIII, and the full text of correspondence between the papal legate and the English court. The second letter acknowledges receipt of Gaudin's response and expresses satisfaction with its thoroughness. The third and fourth letters, dated 1303 and 1306 respectively, continue the operational relationship under Jacques de Molay (Grand Master from 1298). The 1306 letter references 'the deterioration of relations' between Philip and the Templar leadership over a financial dispute and asks for assurance that 'the agreements of the preceding ten years remain in force and that no record of them will pass to unfriendly hands.' The 1306 letter is thus the dissolution's immediate context: Philip was asking for reassurance that the Templars would not use what they knew against him. The dissolution, the following year, suggests he did not receive satisfactory assurance.",
        "rejected": "The Philip IV letters reveal that he had been working with the Templars as spies for many years before the dissolution. He used them to gather information about the Pope and other rulers. When this relationship broke down, the dissolution followed. The letters provide documentary evidence for what historians had suspected about Philip's motivations."
    },
    {
        "prompt": "How does the novel handle the question of Elena's biological identity?",
        "chosen": "Elena's biological identity — her origins as the daughter of Rosa Castillo of Havana, entrusted to Arturo in 1976 — is the novel's most personal mystery, running in parallel with the external Codex mystery without intersecting it until the final third. The handling is deliberately restrained: Elena has known, since her mid-thirties, that there is an unanswered question (the Havana letter in the closet), and has chosen, with Arturo, not to open it. This is not passivity but a specific kind of protective choice, and the novel respects it. The question opens when the crisis makes protective withholding unsustainable: Arturo, facing the possibility of not returning from the Everglades, tells Elena everything in the galley before departure. The scene is rendered with particular care: Elena receives the information sitting at the table with both hands flat on the surface, very still, listening. She does not weep or perform the revelation. She asks two specific questions about Rosa Castillo: whether she was well and whether she knew what was happening when she gave Elena away. Arturo answers both honestly. The biological family in Havana — Rosa's surviving sister and her children — is identified by the time of the epilogue, and Elena's first video call with them is the novel's final personal resolution. Arturo does not attend. It is not his call to make.",
        "rejected": "Elena discovers her biological origins when Arturo finally tells her about Rosa Castillo before the voyage. She learns that her mother was Cuban and has family still living in Cuba. This is an emotional revelation that resolves a lifelong question. In the epilogue Elena makes contact with her biological family in Havana."
    },
]

# Load existing pairs and append
existing_path = os.path.join(DATA_DIR, "rlhf_pairs.jsonl")
existing_pairs = []
with open(existing_path, encoding="utf-8") as f:
    for line in f:
        existing_pairs.append(json.loads(line))

all_pairs = existing_pairs + EXTRA_RLHF
with open(existing_path, "w", encoding="utf-8") as f:
    for pair in all_pairs:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")
print(f"Total RLHF pairs: {len(all_pairs)}")
print(f"  Size: {os.path.getsize(existing_path) / 1024:.1f} KB")

# ---------------------------------------------------------------------------
# Additional instruction prompts
# ---------------------------------------------------------------------------

EXTRA_INSTRS = [
    {
        "instruction": "Write a night watch scene on the Miss Biscayne in the style of the novel.",
        "input": "Jake is on deck alone at 3 AM, two days from Cayo Espiritu.",
        "output": "The watch changed at three and he took it.\n\nNacho had set the boat well before going below: the heading steady, the sail trim good, the autopilot holding her course with the light corrections of a system that was paying attention so he did not have to. The boat moved through the dark water with the quality of motion you get from a well-found vessel in a settled sea: purposeful, almost effortless, the bow lifting slightly to each swell and settling again.\n\nHe stood at the helm and looked at the stars.\n\nThe stars south of the Florida Straits are the stars before the lights. He had grown up under city sky and had not known, until his first time on the open water at night, what the sky looked like when no one was arguing with it. What it looked like was: everything. An uncountable presence. Not romantic. Not comforting. Just there, in the way that very large things are there: regardless of your feelings about them.\n\nHe thought about Diego de Almeida standing a similar watch, on a different vessel, in a different century, on the same water.\n\nNot the same exactly. The same physically — same latitude, same sea — but different in the ways that seven hundred years makes different. Different stars in the sense that the stars had been in different positions. Different wind in the sense that the climate had been different. The same water.\n\nDiego had known where he was going. He had the coordinates in his head. He had the Codex mostly complete. He had thirty men on two vessels and a hold full of lead-lined oak boxes.\n\nJake had the Codex, decoded, on a printed sheet in the chart table. He had coordinates in the GPS. He had four people and a dive bag.\n\nThe sea didn't care about the difference.\n\nHe stood his watch."
    },
    {
        "instruction": "Write a scene in the style of the novel where a character reads something that changes everything.",
        "input": "Arturo is in his back room in 2024. He has just placed the modal cipher grille over the final page and read the coordinate sequence for the first time.",
        "output": "He put the grille down.\n\nHe sat back in his chair.\n\nThe coordinate string was on the yellow pad in his own handwriting, written out digit by digit over the course of four hours as each phrase of the modal sequence resolved. He had been very careful. He had checked each mode identification three times. He had not allowed himself to look at what the string might represent until it was complete.\n\nIt was now complete.\n\nHe opened the mapping application on his laptop and typed in the coordinates.\n\nThe map panned south and east. It crossed Miami, crossed the Florida Straits, moved over the flat blue of the Caribbean. It settled on a small irregular shape in the Windward Passage between Cuba and Hispaniola.\n\nThe island had a name.\n\nCayo Espiritu.\n\nHe sat and looked at it for a long time. He was thinking about Diego de Almeida in Porto in 1315, writing his final document at a table under a lamp, in a room that was cold in November. Diego had known that he was writing for a reader he would never identify, in a time he could not guess, in a language of cipher that might outlast the understanding of everyone alive when he wrote it.\n\nDiego had written it anyway.\n\nThirty-four years. The lamp. The facsimile pages. The back room of La Luz de los Libros while Miami went about its business above and around and outside.\n\nArturo looked at the island on the screen.\n\nHe thought: adequate.\n\nHe thought: the work was worth doing.\n\nHe closed the laptop carefully. He sat for another few minutes in the quiet. Then he turned off the lamp, locked the back room, and went upstairs to tell Elena."
    },
    {
        "instruction": "Explain what makes The Everglades Cipher an example of historical fiction rather than alternate history.",
        "input": "",
        "output": "Historical fiction and alternate history are often confused but are structurally distinct.\n\nAlternate history posits a departure from the documented record at a specific point and explores the consequences: what if the Templars had survived? What if Philip IV had been defeated? It is fundamentally a counterfactual exercise.\n\nHistorical fiction works within the documented record, using the gaps, ambiguities, and documented mysteries in that record as the space within which the fictional story operates. It does not contradict the historical record; it proposes an explanation for what the historical record does not explain.\n\nThe Everglades Cipher is historical fiction in this second sense. The La Rochelle fleet's disappearance is a documented fact — the fleet was gone on the morning of October 13, 1307, and no record of its destination survives. The Codex Almeida proposes an explanation for where a portion of that fleet went. Philip IV's intelligence networks and his specific relationship with the Templar Order are subjects of genuine historical debate, with substantial scholarly literature on what Philip knew and when. The Philip IV letters in the archive propose specific documentary evidence for positions in that debate. The connections between the Templar dissolution, the Order of Christ, and the Portuguese Age of Discovery are documented in general outline; the novel proposes specific mechanisms for how navigational knowledge was transmitted.\n\nNone of these proposals contradict documented fact. They all occupy the space that the documented record leaves open. This is what historical fiction does: it uses the past's genuine gaps as narrative real estate, with the discipline not to fill those gaps with things that are known to be false."
    },
    {
        "instruction": "Write a short scene depicting Elena giving her first public statement about the archive discovery.",
        "input": "Elena speaks at a press conference in Nassau, Bahamas, three months after the discovery.",
        "output": "She had prepared four sentences.\n\nThe room was fuller than she had expected. Cameras in the back. The archaeology team to her left, looking variously composed and not-quite-composed. The Bahamian cultural heritage officer to her right, who had given a statement about jurisdiction and cooperation that had been both careful and gracious.\n\nElena adjusted the microphone.\n\n'The archive at Cayo Espiritu contains two hundred and twelve documents from the early fourteenth century,' she said. 'They are in good condition. They are being examined by an international team of scholars under protocols agreed between the governments of the Bahamas, Portugal, France, and the Vatican. The examination will take years. I expect the results to be significant.'\n\nShe paused.\n\n'My father spent thirty-four years on the work that led to this discovery. He is here today.' She did not gesture toward Arturo in the front row. 'He would describe the discovery as adequate. I think he is, as usual, being precise.'\n\nShe stepped back from the microphone.\n\nThe questions began. She answered them in the way that scientists answer things: accurately, with qualifications for uncertainty, and without the performance of either drama or false modesty. She described what the archive contained. She said what was known. She said what was not yet known. She said when she expected to know more.\n\nArturo, in the front row, listened with his hands folded and did not say anything.\n\nShe glanced at him once.\n\nHe nodded."
    },
    {
        "instruction": "Describe the grille cipher technique as Arturo would explain it to a non-specialist.",
        "input": "Elena has asked Arturo to explain the grille cipher simply, in their apartment kitchen.",
        "output": "'Imagine you have a piece of paper with holes cut in it,' Arturo said.\n\nElena poured coffee for both of them and sat down.\n\n'You put the paper with holes over a page of the book. The holes show you certain letters. You read only the letters the holes show. The rest of the text is what Diego calls — in the cipher's own terminology, which I translated over several months — the covering field. It looks like ordinary text. It is ordinary text. It is also a container for the text the holes reveal.'\n\n'How do you know where to put the holes?' she said.\n\n'The geometry of the holes is encoded in the marginalia. The margins of the Codex have annotations that look like a copyist's reference marks — corrections, section divisions, that kind of thing. They are not those things. They are a coordinate system. The coordinates tell you the shape and position of the grille.'\n\n'So you need the marginalia to make the grille, and you need the grille to read the hidden text.'\n\n'Yes.'\n\n'And if you don't know to look at the marginalia as coordinates—'\n\n'You read a perfectly ordinary fourteenth-century navigation manuscript,' Arturo said. 'Which is what every previous reader did. For seven hundred years.'\n\nShe looked at him.\n\n'And nobody asked why there was musical notation in a navigation manual?'\n\n'Devotional texts often included liturgical music. It was not unusual. It was,' Arturo said, 'placed there deliberately to be not unusual. Diego was very good.'"
    },
    {
        "instruction": "Write a character study of Victor Andrade that presents him with complexity and internal logic.",
        "input": "",
        "output": "Victor Andrade is sixty-one years old and has been in real estate development in South Florida for thirty-five years. He is not, in his own understanding, a villain. He is a person who has spent three decades learning that the world works by leveraging information before anyone else has it, and he has applied this principle consistently and successfully. The Cayo Espiritu opportunity is, to him, exactly what his career has prepared him for: a property that is not yet on any development radar, in a jurisdiction that is navigable, with a specific commercial application (luxury eco-resort, private island, historically-themed experience) that he has been developing in his mind since he first heard about Arturo Vasquez-Cortez's research from an academic contact three years earlier.\n\nHe is not interested in the archive's contents. He has no particular investment in medieval history or the Knights Templar. He is interested in what the archive represents in terms of property rights and development opportunity. The Philip IV letters are, to him, a complication rather than a discovery — the kind of thing that attracts government attention and delays timelines.\n\nHis use of coercion — having Arturo removed from circulation until the coordinates could be obtained — is, in his moral framework, proportionate. He does not harm Arturo. He instructs that Arturo be held comfortably and returned uninjured once the information is transferred. This distinction matters to him.\n\nHe is not wrong that the distinction matters. He is wrong about everything else.\n\nThis is his limitation as a character and as a person: he understands leverage but not value. He can calculate what something is worth in a real estate pro forma. He cannot see what it means."
    },
    {
        "instruction": "Analyze the use of the Miami landscape in The Everglades Cipher.",
        "input": "",
        "output": "Miami in The Everglades Cipher is rendered as a specific, complicated, contemporary city rather than as backdrop or cliché. The city the novel describes has several distinct registers that correspond to different characters and storylines.\n\nThe Little Havana register — Arturo's register — is a neighborhood with deep historical memory and a specific relationship to Cuban exile politics, rendered through the details of daily commercial life: the ventanitas, the bookshop, the Dominican repairman next door, the Friday evening conversations in Spanish over the fence. This Miami is continuous and locally rooted.\n\nThe Coconut Grove register — Jake's register — is the older suburb that the city has absorbed without entirely digesting, with its nautical history and bayfront identity and the specific character of a neighborhood that is simultaneously wealthy and informal, established and impermanent. Jake's office above a dry cleaner and his houseboat at Dinner Key are accurate to this register.\n\nThe Brickell-Wynwood register — Andrade's Miami — is the city of capital flows and development cycles, where the skyline changes every five years and the buildings cost extraordinary sums and the residents are transitional by design. This Miami is the novel's implicit antagonist: the Miami that turns land into abstraction and value into a financial instrument.\n\nThe Everglades register is the city's geographical edge and moral horizon: the place that development cannot cross, the landscape that enforces its own logic regardless of what the city is doing on its northern margin. Elena's work on the reef and Jake's understanding of the Everglades rescue are both products of knowing that Miami does not end at its own boundary — that the landscape around it is real and has claims that do not defer to the city's preferences."
    },
    {
        "instruction": "Write a brief passage from Diego de Almeida's point of view as he sails away from Cayo Espiritu for the last time.",
        "input": "",
        "output": "The island was small from this distance.\n\nHe watched it from the stern until it was indistinguishable from the other low shapes on the horizon, then until the horizon was empty of everything except sea.\n\nHe had been here four times. The first time to survey it, alone in a fishing vessel, to confirm that what the charts suggested was what the island was. The second time with the first cargo — forty-three boxes, the most urgent materials, the ones whose loss would have been most immediately harmful. The third time with the main cargo: 169 boxes over three days, the crew unloading them into the passage by small boat and the swimmers taking them to the air pocket at low tide. The fourth time, last month, to confirm the sealing and to place the Codex.\n\nThe Codex was there now. Sealed in its own container. Addressed to no one, because there was no one to address it to. The future reader was unidentified and unidentifiable — they could be anywhere, at any distance in time, speaking any language, operating under any conditions. Diego had designed the cipher to work without an institutional guardian, without any inherited context, with only the document and the patience to decode it.\n\nHe thought: it will be enough. Or it will not be, and nothing else would have been either.\n\nThe island was gone behind the horizon.\n\nHe turned to face forward, toward Porto, toward home.\n\nThe sea was large and the wind was good and the work was done.\n\nHe began."
    },
]

# Append to instruction prompts
instr_path = os.path.join(DATA_DIR, "instruction_prompts.jsonl")
existing_instrs = []
with open(instr_path, encoding="utf-8") as f:
    for line in f:
        existing_instrs.append(json.loads(line))

all_instrs = existing_instrs + EXTRA_INSTRS
with open(instr_path, "w", encoding="utf-8") as f:
    for item in all_instrs:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")
print(f"Total instruction prompts: {len(all_instrs)}")
print(f"  Size: {os.path.getsize(instr_path) / 1024:.1f} KB")

# Final size summary
total = sum(os.path.getsize(os.path.join(DATA_DIR, f)) for f in os.listdir(DATA_DIR))
print(f"\nTotal data directory: {total / 1024:.1f} KB ({total / 1024**2:.2f} MB)")
