"""
Generate training data for The Everglades Cipher fine-tuning notebook.
Run: python generate_training_data.py
Output: data/rlhf_pairs.jsonl, data/instruction_prompts.jsonl, data/pretraining_chunks.jsonl
"""
import json
import os
import glob
import textwrap

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
CONTENT_DIR = os.path.join(os.path.dirname(__file__), "content", "the-everglades-cipher")
os.makedirs(DATA_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# RLHF PAIRS
# ---------------------------------------------------------------------------

RLHF_PAIRS = [
    {
        "prompt": "Who is Jake Malone and what is his profession?",
        "chosen": "Jake Malone is a private investigator based in Coconut Grove, Miami. He is a former Miami-Dade Police detective who left the department after a series of events he is not inclined to discuss and set up his own investigation firm. He operates from an office above a dry cleaner on Tigertail Avenue and lives on a houseboat called the Reluctant Witness moored in the Dinner Key marina. His practice focuses on background checks, due diligence, and the occasional missing persons case. He takes the Vasquez-Cortez case because the client asks in a way he cannot dismiss.",
        "rejected": "Jake Malone is a detective who solves crimes in Miami. He has a lot of experience and knows how to find people. He lives on a boat and works from an office. He is the main character of The Everglades Cipher."
    },
    {
        "prompt": "What is the Codex Almeida?",
        "chosen": "The Codex Almeida is a fourteenth-century Portuguese manuscript created by Diego de Almeida, a navigator working in service of the Knights Templar. It is a navigation document that conceals, within a two-layer cipher system, the precise geographic coordinates of a hidden archive of Templar documents sealed in a Caribbean sea cave in 1313. The outer layer uses a grille cipher — a physical template which, placed over the manuscript's pages, reveals the concealed navigation text. The inner layer uses a modal cipher embedded in the document's musical notation, in which each passage's church mode encodes a coordinate digit. Arturo Vasquez-Cortez spent thirty-four years decoding it.",
        "rejected": "The Codex Almeida is a secret document from the Middle Ages. It has codes in it that lead to a treasure. Arturo found it and spent many years trying to decode it. The codes were eventually solved and they found the treasure at the end."
    },
    {
        "prompt": "How does the Phrygian dominant mode connect the cipher to the cave?",
        "chosen": "The Phrygian dominant mode (the fifth mode of the harmonic minor scale, characterized by a flattened second degree) is the mode Diego de Almeida uses to encode the final location confirmation in the Codex's musical cipher. It is also the acoustic resonance produced naturally by the Cayo Espiritu cave system, due to the cave's particular geometry and the way water movement through the sea passage excites standing waves at that specific interval. This means that a decoder who arrives at the correct location hears the cave produce, in its own natural sound, the same musical interval that the cipher uses to identify the site — the location announces itself in the cipher's own language. Arturo identifies this correspondence as the 'proof of arrival' that Diego built into the system.",
        "rejected": "The Phrygian mode is a type of music scale. The cave happens to produce this sound naturally, which is a coincidence that helps confirm they found the right cave. When they heard the sound it matched the cipher and they knew they were in the right place."
    },
    {
        "prompt": "What role does Elena Vasquez-Cortez play in the novel?",
        "chosen": "Elena Vasquez-Cortez is both the client who hires Jake Malone and the character whose personal arc — the search for her biological origins — runs parallel to the external investigation. She is a forty-eight-year-old marine biologist at the University of Miami, Arturo's adopted daughter, and the daughter of Rosa Castillo, a Cuban woman who entrusted the infant Elena to Arturo in 1976 when he was leaving for the United States. She does not know her origins until the novel's final third. Her professional expertise in marine ecosystems informs the novel's ecological subplot. Her relationship with Arturo — fifty years of mutual protective withholding finally resolved in a kitchen conversation — is the novel's deepest emotional subject.",
        "rejected": "Elena is Arturo's daughter who hires Jake to find her father. She is a scientist who knows about marine biology. She also discovers her real family origins during the story. She is important to the plot because without her Jake would not have taken the case."
    },
    {
        "prompt": "Describe the historical significance of Philip IV's dissolution of the Knights Templar.",
        "chosen": "The dissolution of the Knights Templar by Philip IV of France (1307-1312) was a political operation that ended the most powerful military-religious order in medieval Europe and, in the novel's interpretation, a records management crisis. Philip IV arrested the entire French Templar leadership on October 13, 1307, on charges of heresy extracted through torture. The Council of Vienne formally dissolved the Order in 1312 and Grand Master Jacques de Molay was burned at the stake in 1314. The novel proposes — supported by the fictional Philip IV letters in the Cayo Espiritu archive — that Philip had been running intelligence operations through the Templars since 1296, and the dissolution was motivated not only by his debts to the Order and his hostility to papal power, but by the need to destroy an organization that had accumulated dangerous knowledge about his own court affairs. The Order had become an intelligence risk.",
        "rejected": "Philip IV dissolved the Knights Templar because he owed them money and wanted to take their property. He accused them of heresy and had them arrested and tortured. This was an important historical event because it ended a powerful medieval organization. The letters found in the novel's archive suggest there were additional motivations."
    },
    {
        "prompt": "What is the Order of Christ and how does it connect to the novel's historical narrative?",
        "chosen": "The Order of Christ was a Portuguese military-religious order founded by King Denis I in 1319, established as the explicit successor to the Knights Templar following the Templar dissolution. Denis I refused to execute the Templar dissolution decree and instead absorbed the Portuguese Templar personnel and assets into this new Order. The Order of Christ subsequently became the institutional patron of Portuguese maritime exploration in the fifteenth and sixteenth centuries — Henry the Navigator was a member and later Grand Master. In the novel, the connection is direct: Diego de Almeida's work for the Templar Order feeds into the navigational knowledge that, transmitted through the Order of Christ, underlies the Portuguese Age of Discovery. The Codex Almeida is both a product of Templar cartographic intelligence and an ancestor of the navigational science that produced Vasco da Gama and Magellan.",
        "rejected": "The Order of Christ was created to replace the Knights Templar in Portugal. It was important for navigation and exploration. In the novel it connects the medieval Templar story to the Age of Discovery. Diego de Almeida was part of this tradition of Portuguese navigation."
    },
    {
        "prompt": "How does Nacho Reyes contribute to the investigation?",
        "chosen": "Nacho Reyes is Jake's oldest friend — they have been friends since they were twelve years old in Hialeah — and operates a dive charter business from Big Pine Key. His contributions are practical and decisive: he provides the boat (the Miss Biscayne), the crew, and thirty years of logged dive records from the waters around Cayo Espiritu that have accumulated without Nacho realizing what he was documenting. When Jake explains what he is looking for, Nacho locates three log entries noting anomalous underwater acoustic phenomena at a specific site: 'tone from somewhere forward, like a held organ note.' These records provide the initial triangulation. His daughter Sofia, a professional dive instructor, performs the initial underwater survey of the archive cave.",
        "rejected": "Nacho Reyes is Jake's friend who helps with the boat part of the investigation. He knows the Caribbean waters well from his dive business and helps them find the right island. Without him they would not have been able to make the voyage. His daughter also helps by diving in the cave."
    },
    {
        "prompt": "What is the setting of La Luz de los Libros?",
        "chosen": "La Luz de los Libros (The Light of Books) is Arturo Vasquez-Cortez's antiquarian bookshop in Little Havana, Miami. It occupies the ground floor of a 1940s building on Calle Ocho (Eighth Street), in the stretch of Little Havana between the Orange Bowl stadium site and Domino Park. The shop is described with the specific sensory texture of a long-established bookshop in a Miami neighborhood: wooden shelves floor-to-ceiling, books in Spanish and Portuguese and English and French organized by Arturo's own system, the particular quality of late afternoon light through the west window, the smell of old paper and the shop's air conditioning. The Codex Almeida has been in the back room, in a climate-controlled manuscript box, since 1989. Arturo has worked on it every evening for thirty-four years after closing time, at a worktable in the back room, under a good lamp.",
        "rejected": "La Luz de los Libros is the name of Arturo's bookshop in Little Havana in Miami. It is an old bookshop where he worked for many years. The Codex Almeida was kept there. It is an important location in the novel because this is where the investigation begins."
    },
    {
        "prompt": "What is the significance of the Everglades fish camp in the novel?",
        "chosen": "The Everglades fish camp is where Arturo is held captive during the novel's middle section. It is located in the southern Everglades, accessible only by airboat, on a tributary of the Shark River. The camp belongs to a network of properties operated by the novel's antagonist, Victor Andrade, who uses it for operations that benefit from geographical isolation. The Everglades setting in this section carries the specific sensory and ecological weight of the actual landscape: the sawgrass prairie, the mangrove tunnels, the afternoon thunderstorm columns visible for thirty miles across flat water, the ibis flights, the alligators. The rescue operation — Jake and Nacho coming in by airboat at night — uses the Everglades landscape as a genuine tactical challenge: the same isolation that makes the camp useful as a prison makes it difficult to approach undetected. Arturo, when found, is physically unharmed but has spent eleven days with his manuscript notes.",
        "rejected": "The Everglades fish camp is where the bad guys are keeping Arturo prisoner. Jake has to find and rescue him from this location. The Everglades are a wild and remote area which makes it a good place for criminals to hide. Jake rescues Arturo and they escape."
    },
    {
        "prompt": "How does Victor Andrade's motivation differ from the other antagonists?",
        "chosen": "Victor Andrade is the novel's primary antagonist and his motivation is specifically real estate and development: he wants the Cayo Espiritu site as the anchor property for a planned Caribbean development project. His interest in the Codex Almeida is purely instrumental — he does not care about the historical content of the archive; he wants the island coordinates to secure the property before competing interests (academic, governmental, or religious) can establish any claim. This distinguishes him from the secondary antagonists, who have institutional or ideological interests in the archive's contents: Father Benedetto Calvino (Vatican) wants the Philip IV letters suppressed because they document a relationship between the papacy and Philip IV that the Church would prefer remained obscure; the Cuban intelligence contact wants the documentation of pre-revolutionary Cuban aristocratic families that may be in the archive. Andrade is, in this structural sense, the simplest antagonist: the one who just wants the land.",
        "rejected": "Victor Andrade is the main villain who wants to use the Cayo Espiritu island for development. He kidnapped Arturo to get the location. The other villains have different motivations related to the historical documents. Andrade is the most dangerous because he will do whatever it takes to get what he wants."
    },
    {
        "prompt": "Describe Jake Malone's investigative method.",
        "chosen": "Jake's investigative method is defined by the discipline of working from what he knows rather than from what he suspects. He is not a dramatic investigator — he does not develop theories and pursue them; he develops questions and answers them one at a time, in order, without committing to a direction until the evidence requires it. He is very good at reading people: not through intuition as a mystical quality but through sustained attention, the accumulation of specific observable details (how people manage silence, what they do with their hands when they mention a particular name, whether their account has the texture of something lived or something constructed). He is a thorough reader of public records: property transfers, corporate filings, court documents, the kinds of paper trails that people generate by living and operating in a city over decades. He is patient. He does not press when pressing will close off information, and he waits without apparent effort.",
        "rejected": "Jake is a classic hardboiled detective who uses his instincts and street knowledge to solve cases. He is very observant and can tell when people are lying. He does not trust the police and works alone. He is good at finding people who do not want to be found."
    },
    {
        "prompt": "What is the ecological significance of the Florida Keys reef system in the novel?",
        "chosen": "Elena's research focus on the Florida Keys reef system and Nacho's thirty years of dive logs from those waters serve the novel's ecological subplot: the ongoing decline and partial recovery of the Florida Reef Tract, the only living coral barrier reef in the continental United States. Elena's work tracks bleaching events (coral mortality from thermal stress), the recovery dynamics of elkhorn and staghorn coral populations (both listed as threatened under the Endangered Species Act), and the interaction between water quality, runoff, and reef health. The ecological narrative runs in parallel with the historical narrative: both are concerned with the question of what survives, and under what conditions. Nacho's logs, accumulated for thirty years without any consciousness of their eventual use, are evidence of both the reef's health history and the underwater acoustic anomaly at Cayo Espiritu — the same document proves two unrelated things, which is the kind of archival gift that the novel presents as characteristic of patient long-term record keeping.",
        "rejected": "The Florida Keys reef is important as part of the setting and Elena's work as a marine biologist. She studies the reef and is concerned about its health. This connects to environmental themes in the novel. Nacho's dive logs also help with the investigation because they recorded information about the cave location."
    },
    {
        "prompt": "What is the timeline structure of the Codex Almeida sections?",
        "chosen": "The Codex Almeida historical interludes are written in the third person, in a register that mimics the texture of documentary historical fiction: present tense, spare, with specific dates. They begin in 1303 with the first signs of Philip IV's hostility toward the Templar Order and follow Diego de Almeida from his initial assignment to transfer the archive materials through his years of navigation in the Atlantic and Western Mediterranean. The key dates in the Diego sections are: 1303 (initial mission assignment), 1307 (October 13, the arrests; Diego is at sea and learns by ship messenger), 1308-1311 (the archive transfer voyages, in stages, multiple sailings), 1312 (final confirmation that the archive is sealed and the site coordinates embedded in the Codex), and 1315 (Diego in retirement in Porto, writing his final document — an account of the enterprise addressed to an unknown future reader). The 1315 final section is the historical thread's emotional resolution: a man who has done important work he cannot tell anyone about, writing it down for whoever will eventually read it.",
        "rejected": "The historical sections follow Diego de Almeida over many years as he completes his mission. They span from before the Templar dissolution to after it. Diego eventually completes the task and hides the archive. The historical sections alternate with the present-day investigation."
    },
    {
        "prompt": "What is the relationship between Arturo and Diego de Almeida across centuries?",
        "chosen": "The relationship between Arturo and Diego is the novel's central structural conceit: two archivists, seven centuries apart, engaged in the same fundamental act — preserving something important from destruction, with patience and precision, and trusting that the work will eventually find its reader. Diego creates the system; Arturo decodes it. Diego addresses his final document to an unnamed future reader who may, centuries later, understand why the work mattered. Arturo is that reader. The novel makes this correspondence explicit in the epilogue: Arturo's published scholarly paper on the Codex closes with an observation about the specific kind of communication that archival work represents — not a message sent to a known recipient, but a message left for whoever has the patience and preparation to find it. 'Diego did not know me,' Arturo writes. 'He did not know when I would exist, or whether I would. He knew only that the work was worth doing, and that doing it correctly was the best chance that it would eventually matter. It is enough.'",
        "rejected": "Diego created the Codex and Arturo decoded it 700 years later. They are connected by the archive and the cipher. Arturo feels a connection to Diego through the work of decoding. This relationship across time is one of the novel's main themes."
    },
    {
        "prompt": "What is the significance of the Calle Ocho setting for the novel's themes?",
        "chosen": "Little Havana's Calle Ocho serves as the novel's ground-level community: the Cuban-American Miami that is neither the tourist-facing image of the city nor the financial and real estate abstraction. Arturo has operated his bookshop on this street since 1973, which places him in the continuous human history of that community — through the Mariel boatlift, through the Elian Gonzalez crisis, through five decades of political and generational change in the Cuban diaspora. The street's specific detail — the ventanitas (walk-up coffee windows) serving cortaditos, Domino Park, the preserved street art — is rendered with the specificity of a place that has been observed over decades rather than researched for a scene. Elena grew up above this street. The investigation begins and ends here. The final scene of the epilogue — Arturo back in his bookshop, working at the back table, with a new manuscript problem in front of him — is set here because this is where the novel's values live: sustained attention, the dignity of small-scale work, the community of the bookshop.",
        "rejected": "Calle Ocho is in Little Havana where Arturo's bookshop is located. It is an important setting because it represents the Cuban-American community in Miami. The setting helps establish the cultural background of the characters. Elena grew up here and it is an important part of the story."
    },
    {
        "prompt": "How does the novel handle the question of who 'owns' the Templar archive?",
        "chosen": "The question of the archive's ownership and jurisdiction is a genuine legal and political complication that the novel does not resolve tidily. Multiple institutional actors assert claims: the Bahamian government (as the nation with jurisdiction over Cayo Espiritu's maritime zone), the Vatican (as the institution that acquired Templar assets after the dissolution), the Portuguese government (as the successor state to the Kingdom of Portugal, whose Order of Christ inherited the Templar mission), and several academic institutions that argue for international archaeological heritage status. The novel's position — expressed through Elena, who is the character best placed to hold it — is that the question of custody should follow the question of purpose: who will take the best care of the documents and ensure their scholarly accessibility? The Philip IV letters create additional complications because their contents are politically sensitive for living institutions. The novel ends with the legal framework still being negotiated, which is realistic rather than evasive.",
        "rejected": "The ownership of the archive is disputed between several parties. The legal resolution is complicated because many different groups have claims. The novel does not fully resolve who owns the archive but suggests it should be preserved for scholarship. This is an important theme about who gets to control history."
    },
    {
        "prompt": "Describe the musical knowledge that underlies Diego's cipher system.",
        "chosen": "Diego de Almeida's cipher uses the medieval eight-mode system of Gregorian plainchant, in which each mode had a fixed numerical value: Dorian (1), Hypodorian (2), Phrygian (3), Hypophrygian (4), Lydian (5), Hypolydian (6), Mixolydian (7), Hypomixolydian (8). The musical notation at the end of the Codex encodes geographic coordinates by writing successive phrases in specific modes; reading the mode-number sequence produces the coordinate string. The system was available to Diego because Templar liturgical practice maintained the modal system at a time when it was already beginning to give way to tonal harmony — the same institutional conservatism that made the Templars valuable as archivists made them reliable custodians of the modal system. The choice of Phrygian dominant for the final confirmation coordinate was additionally elegant: the Phrygian dominant mode's characteristic sound (the flattened second degree, giving the scale its characteristic tension and antiquity) is the specific acoustic mode of the Cayo Espiritu cave, making the musical cipher and the physical site sonically identical.",
        "rejected": "Diego used a musical cipher based on medieval church modes. Each mode corresponded to a number which he used to encode coordinates. The Phrygian mode is special because it also matches the natural sound of the cave. This musical knowledge was available to Diego because of his education in a religious institution."
    },
    {
        "prompt": "What happens to Arturo in the epilogue?",
        "chosen": "In the epilogue, Arturo is back in La Luz de los Libros, working. The arc is quiet: he has spent the months since the Cayo Espiritu excavation consulting with the archaeological team, writing his scholarly paper on the Codex, and — most importantly — having the kitchen conversations with Elena that he had deferred for five decades. Elena's biological family in Havana has been identified (a Castillo family in Vedado, Rosa's surviving sisters), and the Sunday they first make contact by video call is one of the novel's final emotional moments. Arturo does not attend — it is not his call to make — but Elena calls him afterward and tells him what was said, and he listens, and that is the resolution of the relationship: fifty years of protective withholding dissolved into a simple phone call he sits in his back room to receive. The final image is Arturo at his worktable with a new manuscript problem, a seventeenth-century navigational text that arrived from an estate sale in Lisbon. He turns the first page. He begins.",
        "rejected": "In the epilogue, Arturo returns to his bookshop and life goes back to normal. He has helped with the archive excavation and written about the Codex. Elena has found her biological family in Cuba. The novel ends with Arturo working on a new manuscript project, suggesting his work continues."
    },
    {
        "prompt": "What is the significance of the Miss Biscayne voyage?",
        "chosen": "The Miss Biscayne voyage — from Big Pine Key south through the Straits of Florida and into the Windward Passage to Cayo Espiritu — marks the novel's structural turn from investigation to resolution. The voyage chapters draw on the specific texture of Caribbean passage-making: the trade wind swell, the color gradient of the water deepening from green to royal blue past the continental shelf edge, the flying fish, the night watches. Nacho navigates the boat; Jake watches the sea; Elena works on the modal cipher confirmation; Arturo sleeps and, in the night watches, talks with Jake about Diego. The voyage is the period in which the investigation transforms: it is no longer about finding Arturo (found) or preventing Andrade (arrested), it is about completing the task that Diego began in 1307. The novel's emotional logic is that the voyage across the same water Diego crossed seven centuries earlier is the literal and figurative passage from the modern thriller plot into the historical fulfillment. When the island appears on the horizon, the scene is written from Diego's perspective in the final historical interlude — the same coordinates, seen for the last time from the deck of a ship departing — before cutting back to the present.",
        "rejected": "The voyage to Cayo Espiritu is when they travel to find the archive. They sail through the Caribbean on Nacho's boat. The voyage is exciting because they are following the same route as the historical characters. When they arrive at the island they find the cave and discover the archive."
    },
    {
        "prompt": "How does the novel balance thriller mechanics with historical depth?",
        "chosen": "The novel's structural solution to the thriller/historical balance is to keep the thriller plot and the historical narrative in separate registers that periodically converge. The present-day sections are written in the spare, third-limited third-person register of a hard-boiled procedural: short chapters, terse dialogue, forward momentum. The historical interludes are written in a different register — present tense, more lyrical, with the specific sensory weight of Kostova-style historical fiction. The two registers inform each other without interfering: the thriller plot creates the urgency that makes the historical sections feel earned rather than digressive, and the historical sections give the thriller's resolution a weight beyond the simple outcome of the crime plot. The technique is Dan Brown's in skeleton (historical interlude, coded mystery, race to the location) but executed with more patience: the historical sections are not exposition to be consumed and discarded; they are the novel's other heart. Readers who come for the thriller find the history illuminating; readers who come for the history find the thriller keeping them in their seat.",
        "rejected": "The novel combines a detective thriller plot with historical fiction elements. The thriller keeps the pace moving while the historical sections provide depth and context. Dan Brown uses a similar technique with historical mysteries and modern-day investigations. The balance works because both plots come together in the resolution."
    },
]

# Write RLHF pairs
rlhf_path = os.path.join(DATA_DIR, "rlhf_pairs.jsonl")
with open(rlhf_path, "w", encoding="utf-8") as f:
    for pair in RLHF_PAIRS:
        f.write(json.dumps(pair, ensure_ascii=False) + "\n")
print(f"Written {len(RLHF_PAIRS)} RLHF pairs → {rlhf_path}")
print(f"  Size: {os.path.getsize(rlhf_path) / 1024:.1f} KB")

# ---------------------------------------------------------------------------
# INSTRUCTION PROMPTS
# ---------------------------------------------------------------------------

INSTRUCTION_PROMPTS = [
    {
        "instruction": "Summarize the plot of The Everglades Cipher in two paragraphs.",
        "input": "",
        "output": "The Everglades Cipher follows Jake Malone, a Miami private investigator, as he searches for a missing elderly bookseller named Arturo Vasquez-Cortez. Hired by Arturo's adopted daughter Elena, Jake uncovers that Arturo had spent thirty-four years decoding a medieval cipher document called the Codex Almeida — a navigation text created by a fourteenth-century Portuguese navigator named Diego de Almeida, who worked for the Knights Templar. The Codex points to a hidden archive of Templar documents sealed in a Caribbean sea cave in the early 1300s.\n\nThe novel resolves with Arturo's rescue from an Everglades fish camp, followed by a voyage to the island of Cayo Espiritu in the Windward Passage, where the archive is discovered intact in a sea cave. The archive contains 212 documents, including letters from Philip IV of France documenting the real motivations for the Templar dissolution. The epilogue traces the aftermath: archaeological excavation, legal proceedings, Elena's discovery of her biological family in Havana, and the quiet resolution of each character's personal arc."
    },
    {
        "instruction": "Write a character description of Arturo Vasquez-Cortez in the style of the novel.",
        "input": "",
        "output": "Arturo Vasquez-Cortez was seventy-eight years old and knew the difference between what a document said and what he wanted it to say. He had learned this difference at thirty-one, working in the Seville archive, and he had not unlearned it in the forty-seven years since.\n\nHe was small and precise. His hands had the particular quality of hands that have spent a lifetime handling things that matter: the kind of careful deliberateness that is not performance but habit, formed over decades of working with objects whose importance requires that they not be dropped.\n\nHe had run La Luz de los Libros for fifty-four years. He had raised Elena in the apartment above it, alone, without complaint, because complaint had not seemed like the right response to circumstances that were not her fault and not precisely his either. He had found the Codex Almeida in 1989 in a box from a Seville estate sale and had known within the first hour of examination what it was. He had spent the following thirty-four years proving it. He had told no one."
    },
    {
        "instruction": "Explain the medieval mode system and how Diego de Almeida used it as a cipher.",
        "input": "",
        "output": "The medieval eight-mode system is the theoretical framework underlying Gregorian plainchant, inherited from ancient Greek musical theory and formalized in the ninth century. Each mode is defined by a characteristic pattern of whole and half steps and by a final (the pitch on which melodies in that mode cadence). The eight modes are paired into four authentic-plagal pairs: Dorian/Hypodorian, Phrygian/Hypophrygian, Lydian/Hypolydian, Mixolydian/Hypomixolydian, numbered 1 through 8.\n\nDiego de Almeida used this system by writing the coordinate-encoding passage of the Codex Almeida as a series of musical phrases, each in a specific mode. A reader who knows the modal system and can identify which mode each phrase is written in will read the sequence of mode-numbers (1-8) and derive a string of digits. That digit string, interpreted as geographic coordinates in the system Diego used, gives the location of the Cayo Espiritu archive.\n\nThe elegance of the system is that the musical notation is not unusual in a fourteenth-century manuscript — liturgical and devotional texts regularly included plainchant examples. Only a reader who knows to look for the coordinate system hidden in the modal sequence will find it. The Phrygian dominant mode (the fifth mode of the harmonic minor scale, related to but distinct from the medieval Phrygian mode) was chosen for the final confirmation digit because it matches the natural acoustic resonance of the cave — making the cipher self-verifying at the site."
    },
    {
        "instruction": "Write a passage describing Miami's Biscayne Bay in early morning, in the style of the novel.",
        "input": "",
        "output": "The bay in early morning was doing what bays do in early morning: being itself. There was no performance in it. The water was a particular dark green in the channel and a lighter green over the flats, and the horizon where the bay opened into the Atlantic was a thin line that the sun had not yet reached. A heron stood on a piling at the end of the dock. It stood the way herons stand — with the specific patience of a creature for which waiting is not a problem to be solved.\n\nJake sat on the deck of the Reluctant Witness and drank his coffee.\n\nMiami at six in the morning had not yet started being Miami. The city was still in the interval between what it had been the previous night and what it would be when the day got going. Traffic on the Rickenbacker Causeway, visible as moving lights. The early flights over MIA, banking south. The smell of the water, which was not tropical-postcard but specific: the mix of salt and mangrove and the faint industrial underlayer from the port.\n\nIt was a good city if you understood it. Not glamorous, not the city of the postcards. Complicated and hot and in the process of being changed by forces that were not asking its permission. He had been here for twenty-two years. He had not yet solved it. That was part of why he stayed."
    },
    {
        "instruction": "Write a scene where Arturo decodes a key section of the Codex Almeida.",
        "input": "The scene takes place in the back room of La Luz de los Libros, late at night, in 2024.",
        "output": "He had been working on the modal sequence for eleven months.\n\nThe Codex ended with six pages of musical notation. The notation was in neumes — the older notation, before the staff system, the kind that required knowing the melody to read the notation, which meant the notation was not primarily functional. No one had needed to read it for liturgical purposes in 1313. It was there for a reason that was not liturgical.\n\nHe had understood this in 1991 and had spent three years learning enough about medieval modal theory to read it as a cipher might be read. He had spent another two years building the identification key: which neume patterns corresponded to which modal characteristics. He had spent another six years confirming the key against other known examples.\n\nNow he sat under the lamp with the facsimile pages and the key and a legal pad and he worked.\n\nThe first phrase resolved to Hypophrygian. Four.\nThe second phrase to Dorian. One.\nThe third phrase to Lydian. Five.\n\nHe wrote the digits down.\n\nAt three in the morning he had forty-two digits. He arranged them into coordinate pairs and looked at what the coordinates indicated on the digital map on his laptop.\n\nThe island had a name. Cayo Espiritu.\n\nHe sat and looked at it for a long time. He thought about Diego de Almeida sitting somewhere in Porto in 1315, writing the document that Arturo held in facsimile form. Diego had not known when the reader would come. He had known only that the work was worth doing correctly.\n\nArturo turned off the lamp and locked the back room and went upstairs to bed. He did not sleep for three hours. When he slept, he slept well."
    },
    {
        "instruction": "Describe the physical environment of the Florida Everglades as depicted in the novel.",
        "input": "",
        "output": "The Everglades in the novel is the actual Everglades: not swamp in the conventional sense but river. The River of Grass, the Marjory Stoneman Douglas name for it, is accurate: a shallow sheet of freshwater moving imperceptibly south and southwest from Lake Okeechobee to the mangrove coast. Seventy miles wide in places and six inches deep. Moving too slowly to see, fast enough to sustain an ecosystem.\n\nThe approach by airboat from the Tamiami Trail goes through sawgrass first, then into a zone where the cypress begin: bald cypress with their knees emerging from the dark water, draped with bromeliads, the afternoon light filtering through the canopy in a particular greenish way that changes the quality of the air. Anhingas drying their wings on branches above the water line. An alligator on a mudbank, utterly still, with the specific quality of stillness of a creature that has no reason to hurry.\n\nThe fish camp is on a tributary of the Shark River, in the brackish transition zone where freshwater and saltwater meet. The smell is different here: more salt, more organic decay, the particular smell of mangrove roots at low water. The mosquitoes are operational around the clock. The channel is narrow enough that the vegetation closes overhead in places.\n\nAt night the stars over the Everglades are what stars look like when there is no light pollution for thirty miles in any direction. They were what they were before cities."
    },
    {
        "instruction": "Analyze the theme of preservation in The Everglades Cipher.",
        "input": "",
        "output": "Preservation is the novel's deepest thematic concern, operating simultaneously on three levels: archival, ecological, and personal.\n\nAt the archival level, the novel is about what Diego de Almeida and Arturo Vasquez-Cortez share across seven centuries: the conviction that certain things are worth the effort of keeping, that the work of preservation — done carefully, without guarantee of outcome — is itself meaningful. Diego seals the Templar documents in a sea cave and encodes their location in a cipher system designed to survive without an institutional guardian. Arturo decodes the cipher and ensures the archive's scholarly recovery. Both acts are performed by individuals working with patient precision against the likelihood that the work will not matter, or will matter to no one they know, or will only matter centuries after they are gone.\n\nAt the ecological level, Elena's reef research and Nacho's dive logs are both preservation in the same sense: the slow accumulation of careful records that document a living system under pressure. The reef's condition in 2024 is worse than it was in 1990; the records prove this; the records also prove the partial recovery that follows intervention. Preservation here means witnessing accurately and over time.\n\nAt the personal level, both Arturo and Elena have been preserving a relationship by protecting each other from it — withholding the hard questions to maintain the stable form. The novel proposes that this kind of preservation is a false preservation: it keeps the form intact while allowing the substance to desiccate. The resolution comes when they stop preserving and start speaking."
    },
    {
        "instruction": "Write a scene where Jake Malone interrogates a reluctant witness.",
        "input": "The witness is a property records clerk named Gustavo who knows more about Victor Andrade's holdings than he's admitting.",
        "output": "Gustavo had been at the counter for eleven years and had developed the particular expertise of counter staff everywhere: knowing exactly how much information he was required to provide and providing exactly that, no more, with a quality of deliberate inefficiency that communicated something without technically saying it.\n\n'I can give you the public records,' he said.\n\n'I know you can,' Jake said. 'I'm asking about the properties in Homestead that aren't in the public database yet. The ones filed last quarter that haven't been indexed.'\n\nGustavo looked at him.\n\nJake did not look away. He did not lean forward or adjust his posture or do anything that would indicate he had a position on how this was going to go. He just looked at Gustavo and waited.\n\nThis was the part that most people couldn't do: the waiting. Most people needed the conversation to move. They would offer something, concede something, change register. Jake found the waiting straightforward. There was nothing complicated about being still.\n\nGustavo looked down at his keyboard.\n\n'The filings from the last quarter are available for in-person inspection,' he said carefully. 'They're in file room 3B. I can't guarantee they've been cross-referenced with the main index yet.'\n\n'I appreciate that,' Jake said.\n\nHe appreciated it because it was what Gustavo could offer from within the constraints he was operating under, which meant someone had told him something about those files, which meant there was something in those files worth telling him something about.\n\n'Room 3B,' he said. 'Thank you, Gustavo.'"
    },
    {
        "instruction": "Describe the Caribbean island of Cayo Espiritu in the style of the novel.",
        "input": "",
        "output": "Cayo Espiritu was three nautical miles long and perhaps a mile wide at its widest point, low-lying except for a central limestone ridge that ran north to south and rose to perhaps forty feet above the water line at its highest. The ridge was the island's essential structure: the sea cave was on the western face of it, accessible at the water line at low tide, submerged at high tide.\n\nThe island was covered in dry tropical forest: gumbo limbo trees with their peeling red bark, poisonwood and manchineel at the margins (the manchineel fruit toxic, the bark toxic in rain — a useful natural barrier), sea grape and buttonwood in the coastal zone. The beach on the eastern side was white sand over limestone. The western side was ironshore: sharp fossilized coral that made landing without a specific knowledge of the access points a genuinely bad idea.\n\nThe water around it was the clear Caribbean: twenty feet of visibility from the surface, deeper further out. The bottom was rock and coral on the western side, sand on the east. The acoustic phenomenon — the tone from the cave passage, audible as a faint resonance on still days when the swell was running from the right direction — Nacho had logged three times in thirty years of diving nearby, always noting it and never following it.\n\nFrom the deck of the Miss Biscayne, coming in from the north in the mid-afternoon light, the island looked like an island. Limestone and trees and sea. Nothing announced itself. That was, Arturo observed, exactly correct."
    },
    {
        "instruction": "Write dialogue between Jake and Elena as they first examine Arturo's back room.",
        "input": "Jake and Elena enter the bookshop's back room after Arturo's disappearance, looking for evidence of what he was working on.",
        "output": "'He worked here,' Elena said. She said it as a statement of observable fact, not an inference. The worktable was specific: the lamp angled precisely, the facsimile pages in a transparent archival folder, the yellow legal pads stacked with a quality of deliberateness that meant he knew where everything was.\n\nJake looked at the room without touching anything.\n\nThe shelves in here were different from the front of the shop: more systematic. Reference materials grouped by subject. A whole section of medieval maritime history. Portuguese cartography. A run of journals from the Arquivo Nacional Torre do Tombo that went back to the 1990s.\n\n'When did this start?' he said.\n\nElena was looking at the facsimile folder. She hadn't touched it. 'The Seville estate sale was 1989. He told me it was 'an interesting manuscript problem.' He used that phrase for thirty-four years.'\n\n'And you didn't push.'\n\n'He didn't push on my work either,' she said. 'That was how we operated.'\n\nJake looked at the legal pads. The top sheet had columns of numbers and letter-combinations that he didn't immediately recognize. Below them, what looked like coordinate notation.\n\n'Did he ever mention the Knights Templar?'\n\nElena looked at him.\n\n'He used to say that the fourteenth century was a more violent era than people remembered,' she said. 'He said it every time a news cycle started to bother him.'"
    },
    {
        "instruction": "What are the major stylistic influences on The Everglades Cipher?",
        "input": "",
        "output": "The Everglades Cipher draws from six primary stylistic traditions.\n\nFrom James Hadley Chase: the spare, functional prose of the hardboiled tradition, in which Jake's consciousness registers the world in specific observable detail without editorializing; the morally grey protagonist who operates by a code that is not the law's code; dialogue that carries weight through what is withheld as much as what is said.\n\nFrom John Grisham: the institutional texture that grounds the thriller in recognizable systems — property law, archaeological jurisdiction, the specific procedures of a police missing persons investigation; the sense that the real drama is often in the process rather than the confrontation.\n\nFrom Carl Hiaasen: the South Florida specificity — the particular human comedy of Miami's overlapping cultures, the ecological anxiety that runs beneath the surface of every Florida story, the named and rendered real places.\n\nFrom Dan Brown: the structural alternation between the present-day thriller and the historical narrative; the cipher-and-archive mystery that rewards research and patience; the chapter-ending hook.\n\nFrom Elizabeth Kostova: the depth of sensory immersion in historical locations; the sense that place is not backdrop but character; the particular register of scholarly obsession rendered from the inside.\n\nFrom Ruskin Bond: the dignity of small human moments; the subplot characters who have their own inner lives; the prose that finds significance in the ordinary without making a performance of it."
    },
    {
        "instruction": "Write a brief scene depicting the coral reef ecosystem as observed by Elena during a dive.",
        "input": "",
        "output": "She was at twenty feet on the outer edge of the Looe Key spur-and-groove formation and she was watching.\n\nThe brain coral was the size of a small car, mounded, its surface in the distinctive labyrinthine pattern that made it look like the outside of something that was also inside. Around it, the groove was carpeted in what had been, in the 2005 survey, a substantially denser assemblage of soft corals. The recovery was partial. Partial was what you got if the water temperature cooperated and the runoff pressure decreased and the storms came at intervals that allowed recruitment before the next bleaching event.\n\nA parrotfish moved across her field of vision. Blue-green, the size of her forearm, making the specific crunching sound that parrotfish make when they bite coral — not destruction but process, the coral rock passing through the digestive system and emerging as the fine white sand that made Caribbean beaches. The fish was indifferent to her. She was furniture.\n\nShe checked her pressure gauge. She took a note on her slate: three new recruits on the south face of the formation, branching, approximately four centimeters. Small. Possibly significant.\n\nShe wrote the coordinates. She would enter them in the database tonight.\n\nThe database was seventeen years old. It was the most honest record she knew of the reef's actual history. It did not show what she wanted; it showed what was there. That was its value."
    },
]

# Write instruction prompts
instr_path = os.path.join(DATA_DIR, "instruction_prompts.jsonl")
with open(instr_path, "w", encoding="utf-8") as f:
    for item in INSTRUCTION_PROMPTS:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")
print(f"Written {len(INSTRUCTION_PROMPTS)} instruction prompts → {instr_path}")
print(f"  Size: {os.path.getsize(instr_path) / 1024:.1f} KB")

# ---------------------------------------------------------------------------
# PRETRAINING CHUNKS — load novel text and split into ~500-word windows
# ---------------------------------------------------------------------------

def chunk_text(text, words_per_chunk=500, overlap=50):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + words_per_chunk, len(words))
        chunk = " ".join(words[start:end])
        if len(chunk.split()) >= 100:  # skip tiny tail chunks
            chunks.append(chunk)
        start += words_per_chunk - overlap
    return chunks

all_txt_files = sorted(glob.glob(os.path.join(CONTENT_DIR, "*.txt")))
all_chunks = []
for path in all_txt_files:
    with open(path, encoding="utf-8") as f:
        text = f.read()
    for chunk in chunk_text(text):
        all_chunks.append({"text": chunk})

pretraining_path = os.path.join(DATA_DIR, "pretraining_chunks.jsonl")
with open(pretraining_path, "w", encoding="utf-8") as f:
    for chunk in all_chunks:
        f.write(json.dumps(chunk, ensure_ascii=False) + "\n")
print(f"Written {len(all_chunks)} pretraining chunks → {pretraining_path}")
print(f"  Size: {os.path.getsize(pretraining_path) / 1024:.1f} KB")

# ---------------------------------------------------------------------------
# SUMMARY
# ---------------------------------------------------------------------------
total = sum(os.path.getsize(os.path.join(DATA_DIR, f)) for f in os.listdir(DATA_DIR))
print(f"\nTotal data directory size: {total / 1024:.1f} KB ({total / 1024**2:.2f} MB)")
