"""
CodeTreeIndex — extends TreeIndex with code-aware indexing.

Key differences from TreeIndex
-------------------------------
- Stores ``CodePointer`` (line-level) metadata alongside each L1 entry
- Uses a code-specific embedding model (codebert-base) when available
- ``get_raw_chunk(chunk_id)`` reads exact source lines instead of byte ranges
- L2+ super-summaries are generated by qwen2.5-coder:7b (code-aware)
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

from context_optimizer.tree_index import BlockHit, ClusterHit, TreeIndex

if TYPE_CHECKING:
    from .code_pointer import CodeChunk, CodePointer


class CodeTreeIndex(TreeIndex):
    """
    Hierarchical summary index specialised for source-code corpora.

    Parameters
    ----------
    collection_name, persist_directory, depth:
        Same as :class:`~context_optimizer.tree_index.TreeIndex`.
    code_embedding_model:
        HuggingFace model ID for code-semantic embeddings.
        Defaults to ``microsoft/codebert-base``; falls back to
        ``all-MiniLM-L6-v2`` if the model is unavailable.
    """

    # Prompt for L2+ code cluster super-summaries
    _CLUSTER_PROMPT = (
        "Produce a dense semantic summary of what the following code functions/classes do. "
        "Focus on: function names, their purpose, key algorithms, data structures used, "
        "and important API calls. Use short noun phrases separated by semicolons. "
        "No prose, no JSON. Aim for 100-150 tokens.\n\n"
        "Functions/classes:\n{summaries}\n\nCode cluster summary:"
    )

    def __init__(
        self,
        collection_name: str = "code_tree",
        persist_directory: str = "./code_tree_db",
        code_embedding_model: str = "microsoft/codebert-base",
        depth: int = 0,  # 0 = auto
    ) -> None:
        # Resolve embedding model — try codebert, fall back to miniLM
        self._code_embed_model = self._resolve_embed_model(code_embedding_model)

        super().__init__(
            collection_name=collection_name,
            persist_directory=persist_directory,
            block_index=None,  # code uses line pointers, not byte pointers
            embedding_model_name=self._code_embed_model,
            depth=max(2, depth),
        )
        # Map chunk_id -> CodePointer (populated during build)
        self._pointers: dict[str, "CodePointer"] = {}
        self._load_pointers()

    # ── Build ─────────────────────────────────────────────────────────────────

    def build_from_code_chunks(
        self,
        chunks: "list[CodeChunk]",
        cluster_size: int = 4,
        llm: Any | None = None,
        label: str = "",
        auto_depth: bool = True,
    ) -> None:
        """
        Summarize and index *chunks*.

        Pass 1: generate a code summary for each chunk via *llm*.
        Pass 2+: cluster summaries hierarchically (same as TreeIndex).
        """
        from context_optimizer.tree_index import _auto_tree_depth

        _pfx = f"[{label}] " if label else ""

        if auto_depth and self._depth == 2:
            # Recompute depth from actual chunk count
            new_depth = _auto_tree_depth(
                n_blocks=len(chunks),
                cluster_size=cluster_size,
            )
            if new_depth != self._depth:
                self._depth = new_depth
                # Add missing level collections
                import chromadb
                from chromadb.config import Settings
                from context_optimizer.cached_retriever import CachedChromaRetriever

                _dummy = CachedChromaRetriever(
                    collection_name="code_init_dummy",
                    persist_directory=self._persist_dir,
                    embedding_model_name=self._code_embed_model,
                    cache_size=1,
                )
                emb_fn = _dummy.chroma_embedding_fn
                for lvl in range(max(self._levels.keys()) + 1, new_depth + 1):
                    self._levels[lvl] = self._client.get_or_create_collection(
                        name=f"{self.collection_name}_L{lvl}",
                        embedding_function=emb_fn,
                        metadata={"hnsw:space": "cosine"},
                    )
                print(
                    f"{_pfx}[CodeTreeIndex] Auto depth={new_depth} for {len(chunks)} chunks"
                )

        # ── Pass 1: summarize each chunk ──────────────────────────────────────
        l1 = self._levels[1]
        if l1.count() == 0:
            print(
                f"{_pfx}[CodeTreeIndex] Pass 1: summarizing {len(chunks)} code chunks ..."
            )
            ids, docs, metas = [], [], []
            for i, chunk in enumerate(chunks, 1):
                summary = self._summarize_chunk(chunk, llm, _pfx)
                chunk.summary = summary
                chunk.pointer.chunk_id = chunk.chunk_id

                ids.append(chunk.chunk_id)
                docs.append(summary)
                metas.append(
                    {
                        "file_path": chunk.pointer.file_path,
                        "start_line": chunk.pointer.start_line,
                        "end_line": chunk.pointer.end_line,
                        "symbol_name": chunk.pointer.symbol_name,
                        "language": chunk.pointer.language,
                    }
                )
                self._pointers[chunk.chunk_id] = chunk.pointer

                if i % 50 == 0 or i == len(chunks):
                    print(
                        f"  {_pfx}[CodeTreeIndex] Pass 1: {i}/{len(chunks)} chunks",
                        end="\r",
                    )

            l1.add(ids=ids, documents=docs, metadatas=metas)
            self._save_pointers()
            print(f"\n{_pfx}[CodeTreeIndex] L1 ready — {l1.count()} entries")
        else:
            print(
                f"{_pfx}[CodeTreeIndex] L1 already populated ({l1.count()}), loading pointers"
            )
            self._load_pointers()

        # ── Pass 2+: cluster using parent build_from_chunks logic ─────────────
        # Re-use parent's iterative clustering, seeded from the L1 docs
        from context_optimizer.compressor import CompressedChunk as _CC

        # Wrap CodeChunks as CompressedChunks so the parent method works
        l1_data = l1.get(include=["documents"])
        wrapped: list[_CC] = []
        for cid, doc in zip(l1_data["ids"], l1_data["documents"]):
            ptr = self._pointers.get(cid)
            wrapped.append(
                _CC(
                    chunk_id=cid,
                    raw_text=ptr.fetch() if ptr else doc[:800],
                    compressed_summary=doc,
                    index_text="",
                    entities=[],
                    keywords=[],
                    metadata={},
                    original_tokens=len(doc.split()),
                    compressed_tokens=len(doc.split()),
                    compression_ratio=1.0,
                )
            )

        # Only build L2+ (L1 is already done)
        _prev_ids = [c.chunk_id for c in wrapped]
        _prev_docs = [c.compressed_summary for c in wrapped]
        for lvl in range(2, self._depth + 1):
            curr = self._levels[lvl]
            if curr.count() > 0:
                print(f"{_pfx}[CodeTreeIndex] L{lvl} already populated, skipping")
                existing = curr.get(include=["documents"])
                _prev_ids = existing["ids"]
                _prev_docs = existing["documents"]
                continue
            n_clusters = max(1, (len(_prev_ids) + cluster_size - 1) // cluster_size)
            print(
                f"{_pfx}[CodeTreeIndex] Pass {lvl}: {len(_prev_ids)} L{lvl-1} nodes -> {n_clusters} L{lvl} clusters ..."
            )
            new_ids, new_docs, new_metas = [], [], []
            for ci in range(n_clusters):
                start = ci * cluster_size
                end = min(start + cluster_size, len(_prev_ids))
                child_sums = _prev_docs[start:end]
                child_ids = _prev_ids[start:end]
                cluster_id = f"cluster_L{lvl}_{ci:04d}"
                t0 = time.perf_counter()
                if llm is not None:
                    prompt = self._CLUSTER_PROMPT.format(
                        summaries="\n---\n".join(child_sums)
                    )
                    try:
                        resp = llm.invoke(prompt)
                        super_summary = (
                            resp.content if hasattr(resp, "content") else str(resp)
                        ).strip()[:800]
                    except Exception as exc:
                        print(
                            f"{_pfx}[CodeTreeIndex] WARNING L{lvl} cluster {ci}: {exc}"
                        )
                        super_summary = " ; ".join(child_sums)[:800]
                else:
                    super_summary = " ; ".join(child_sums)[:1200]
                elapsed = time.perf_counter() - t0
                print(
                    f"  L{lvl} cluster {ci+1}/{n_clusters} ({len(child_ids)} items)  {elapsed:.1f}s"
                )
                new_ids.append(cluster_id)
                new_docs.append(super_summary)
                new_metas.append(
                    {
                        "child_ids": ",".join(child_ids),
                        "item_start": start,
                        "item_end": end,
                        "level_below": lvl - 1,
                    }
                )
            curr.add(ids=new_ids, documents=new_docs, metadatas=new_metas)
            _prev_ids = new_ids
            _prev_docs = new_docs
            print(f"{_pfx}[CodeTreeIndex] L{lvl} ready — {curr.count()} entries")

    # ── Retrieval ─────────────────────────────────────────────────────────────

    def get_raw_chunk(self, chunk_id: str) -> str:
        """Fetch the source code for *chunk_id* using line pointers."""
        ptr = self._pointers.get(chunk_id)
        if ptr:
            return ptr.fetch()
        # Fallback: try L1 document (the summary)
        result = self._levels[1].get(ids=[chunk_id])
        if result["ids"]:
            return result["documents"][0]
        return ""

    def get_pointer(self, chunk_id: str) -> "CodePointer | None":
        return self._pointers.get(chunk_id)

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _resolve_embed_model(preferred: str) -> str:
        """Return *preferred* if available, else fall back to miniLM."""
        try:
            from sentence_transformers import (
                SentenceTransformer,  # type: ignore[import]
            )

            SentenceTransformer(preferred, cache_folder=None)
            return preferred
        except Exception:
            return "all-MiniLM-L6-v2"

    def _summarize_chunk(self, chunk: "CodeChunk", llm: Any | None, pfx: str) -> str:
        """Generate a natural-language summary of *chunk.source* via *llm*."""
        if not llm:
            # Fallback: return the first 200 chars of source as the "summary"
            return chunk.source[:600]

        prompt = (
            f"Summarize this {chunk.pointer.language} function/class in 50-100 words. "
            f"Focus on: what it does, key parameters, return value, side effects. "
            f"Symbol: {chunk.pointer.symbol_name}\n\n"
            f"```{chunk.pointer.language}\n{chunk.source[:2000]}\n```\n\n"
            "Summary:"
        )
        try:
            resp = llm.invoke(prompt)
            return (resp.content if hasattr(resp, "content") else str(resp)).strip()[
                :600
            ]
        except Exception as exc:
            print(f"{pfx}WARNING: summarization failed for {chunk.chunk_id}: {exc}")
            return chunk.source[:400]

    def _pointer_db_path(self) -> Path:
        return Path(self._persist_dir) / "code_pointers.json"

    def _save_pointers(self) -> None:
        import json

        db = {cid: ptr.to_dict() for cid, ptr in self._pointers.items()}
        self._pointer_db_path().write_text(json.dumps(db, indent=2), encoding="utf-8")

    def _load_pointers(self) -> None:
        import json

        from .code_pointer import CodePointer

        p = self._pointer_db_path()
        if p.exists():
            for cid, d in json.loads(p.read_text("utf-8")).items():
                self._pointers[cid] = CodePointer.from_dict(d)
