apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: ml-dev

configMapGenerator:
  - name: ml-api-config
    behavior: merge
    literals:
      - environment=dev
      - log_level=DEBUG

replicas:
  - name: ml-api
    count: 2
